export const restaurants = [
  {
    info: {
      id: "123008",
      name: "Shanghai Restaurant",
      cloudinaryImageId: "447a5f9473195a0efdc502216fbce4b5",
      areaName: "Borjhar",
      costForTwo: "₹350 for two",
      cuisines: [
        "Chinese",
        "Biryani",
        "Fast Food",
        "Rolls & Wraps",
        "shawarma",
        "North Indian",
      ],
      avgRating: 4.2,
      parentId: "181679",
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 39,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "35-45 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "ABOVE ₹500",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/shanghai-restaurant-borjhar-guwahati-123008",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "788608",
      name: "Street Za",
      cloudinaryImageId: "b14cd9fc40129fcfb97aa7e621719d07",
      locality: "Khaikuchi Road",
      areaName: "Azara",
      costForTwo: "₹300 for two",
      cuisines: [
        "North Indian",
        "Chinese",
        "Rolls & Wraps",
        "Burgers",
        "Pastas",
        "Fast Food",
        "Pizzas",
      ],
      avgRating: 4.1,
      parentId: "8832",
      avgRatingString: "4.1",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 47,
        lastMileTravel: 7.5,
        serviceability: "SERVICEABLE",
        slaString: "45-55 mins",
        lastMileTravelString: "7.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-12 00:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/street-za-khaikuchi-road-azara-guwahati-788608",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "673142",
      name: "Fat Belly",
      cloudinaryImageId: "6614fa9bdbc5559dd5f05aecb2caf980",
      locality: "Sabha Ghar",
      areaName: "Azara",
      costForTwo: "₹300 for two",
      cuisines: [
        "Chinese",
        "Snacks",
        "Pan-Asian",
        "Fast Food",
        "Thai",
        "Tibetan",
      ],
      avgRating: 4.4,
      parentId: "8251",
      avgRatingString: "4.4",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 47,
        lastMileTravel: 7.9,
        serviceability: "SERVICEABLE",
        slaString: "45-55 mins",
        lastMileTravelString: "7.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 23:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/fat-belly-sabha-ghar-azara-guwahati-673142",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "563082",
      name: "Bon Appetit",
      cloudinaryImageId: "swkre08ktyucyeyvhurq",
      locality: "VIP Airport Road",
      areaName: "Borjhar",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian"],
      avgRating: 3.7,
      parentId: "151",
      avgRatingString: "3.7",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 51,
        lastMileTravel: 8.7,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "8.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 21:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "ABOVE ₹550",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/bon-appetit-vip-airport-road-borjhar-guwahati-563082",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "544697",
      name: "Momomia Love In Every Bite",
      cloudinaryImageId: "dnjhmzw3jpahvq2ykzug",
      locality: "VIP Airport Road",
      areaName: "Borjhar",
      costForTwo: "₹250 for two",
      cuisines: ["Momos", "Chinese", "Beverages"],
      avgRating: 4.1,
      parentId: "232865",
      avgRatingString: "4.1",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 51,
        lastMileTravel: 8.7,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "8.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 21:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "ABOVE ₹550",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/momomia-love-in-every-bite-vip-airport-road-borjhar-guwahati-544697",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "569828",
      name: "Flavours Of Darjeeling",
      cloudinaryImageId: "exxe5mnnei7p5lefsmtj",
      locality: "Goalpara Guwahati Road",
      areaName: "Borjhar",
      costForTwo: "₹500 for two",
      cuisines: ["Chinese", "Burgers", "Fast Food"],
      avgRating: 4.2,
      parentId: "340487",
      avgRatingString: "4.2",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 43,
        lastMileTravel: 6.7,
        serviceability: "SERVICEABLE",
        slaString: "40-50 mins",
        lastMileTravelString: "6.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 21:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/flavours-of-darjeeling-goalpara-road-borjhar-guwahati-569828",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "413868",
      name: "Magical Restaurantt",
      cloudinaryImageId: "olfkp4b0uqvzpirk3ev9",
      areaName: "ISBT",
      costForTwo: "₹450 for two",
      cuisines: ["Chinese", "North Indian", "Seafood"],
      avgRating: 4.3,
      parentId: "249920",
      avgRatingString: "4.3",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 51,
        lastMileTravel: 8.1,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "8.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 21:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/magical-restaurantt-isbt-guwahati-413868",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "578685",
      name: "Jai Maa Kamakhya Hyderabad Kitchen",
      cloudinaryImageId: "fnktggyjbcnto08tpucr",
      locality: "VIP Airport Road",
      areaName: "Borjhar",
      costForTwo: "₹400 for two",
      cuisines: ["Indian", "Hyderabadi", "Snacks"],
      avgRating: 4.1,
      parentId: "346798",
      avgRatingString: "4.1",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 47,
        lastMileTravel: 7.7,
        serviceability: "SERVICEABLE",
        slaString: "45-55 mins",
        lastMileTravelString: "7.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "ABOVE ₹1000",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/jai-maa-kamakhya-hyderabad-kitchen-vip-airport-road-borjhar-guwahati-578685",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "642712",
      name: "The Naga Kitchen",
      cloudinaryImageId: "gqxvgrecdgkmshyrieqg",
      locality: "Goalpara Guwahati Road",
      areaName: "Azara",
      costForTwo: "₹400 for two",
      cuisines: ["Naga", "Chinese"],
      avgRating: 4.4,
      parentId: "331479",
      avgRatingString: "4.4",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 47,
        lastMileTravel: 7.7,
        serviceability: "SERVICEABLE",
        slaString: "45-55 mins",
        lastMileTravelString: "7.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-03-11 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹120",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-6adcf766-2094-41a6-8761-f2a9be7968f7",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/the-naga-kitchen-goalpara-road-azara-guwahati-642712",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
];
